RES-13 Add responsive contacts section
proitschool/resume_fe-0001 pull request #16
Opened 2020-09-16 18:30 UTC by Victoria1708

2020-09-17 12:56 UTC, dimasemehuk7 approved these changes
all rigt

2020-09-17 13:00 UTC, proitschool commented
Нужно удалить из комита папку node_modules. Добавь эту папку в .gitignore потом после этого можно будет делать review.

2020-09-20 10:21 UTC, proitschool requested changes

2020-09-20 10:21 UTC, proitschool commented on webapp/src/scss/components/_contacts.scss
> +  @media (min-width: 760px) {
Пустые строки между медиа запросами

2020-09-20 10:21 UTC, proitschool commented on webapp/src/scss/components/_contacts.scss
> +    justify-items: center;
Потеряла отступы

2020-09-20 10:21 UTC, proitschool commented on webapp/src/scss/components/_contacts.scss
> +      @media (min-width: 760px) {
Тут пустые строки потерялиьсь

2020-09-20 10:21 UTC, proitschool commented on webapp/src/scss/components/_contacts.scss
> +    @media (min-width: 760px) {
Breakponts привяжем к тем, которые указаны на странице https://getbootstrap.com/docs/3.4/css/#grid

2020-09-25 15:35 UTC, proitschool requested changes

2020-09-25 18:54 UTC, proitschool approved these changes

2020-09-25 18:57 UTC, merged