res-21 refactor profile styles
proitschool/resume_fe-0001 pull request #20
Opened 2020-10-01 15:52 UTC by dimasemehuk7

2020-10-02 10:25 UTC, proitschool requested changes

2020-10-02 10:25 UTC, proitschool commented on webapp/src/scss/components/_profile.scss
>        grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
Мне кажется тут тоже можно упростить.

2020-11-08 19:00 UTC, proitschool submitted a review, later dismissed

2020-11-10 14:43 UTC, mzhelyaskov submitted a review, later dismissed

2020-11-14 14:38 UTC, proitschool approved these changes

2020-11-14 14:38 UTC, merged