RES-32 add locals styles
proitschool/resume_fe-0001 pull request #26
Opened 2020-10-31 12:55 UTC by dimasemehuk7

2020-10-31 13:03 UTC, proitschool requested changes

2020-10-31 13:03 UTC, proitschool commented on webapp/src/views/index.html
> +<div class="local-items">
local-items -> locals

2020-10-31 13:03 UTC, proitschool commented on webapp/src/views/index.html
> +    <div class="local-items__item {{#if this.active}}active{{/if}}">{{this.name}}</div>
local-items__item -> locals__item

2020-10-31 13:03 UTC, proitschool commented on webapp/src/scss/components/_locals.scss
> +.local-items {
local-items -> locals

2020-10-31 13:03 UTC, proitschool commented on webapp/src/scss/components/_locals.scss
> +  &__item {
```
  &__item {
    color: white;
    text-align: right;
    font-size: 20px;

    &.active {
      color: $color-text-second;
      border-bottom: 2px solid $color-text-second;
    }
  }
```

2020-10-31 13:39 UTC, Victoria1708 commented on webapp/src/views/index.html
> +    <div class="local-items__item {{#if this.active}}active{{/if}}">{{this.name}}</div>
Я б назвала div для кнопок language-buttons або language-toggles, і кожну кнопку language-buttons__button/toggle.

2020-11-01 07:30 UTC, proitschool approved these changes

2020-11-01 07:31 UTC, merged